# Generated by Django 4.2.4 on 2023-08-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('short_descr', models.CharField()),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('price', models.FloatField()),
                ('price_currency', models.CharField(default='JPY')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('website', models.CharField()),
                ('cancel_before', models.DateTimeField()),
                ('tranche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tranche')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(fields=('tranche', 'id'), name='stay_pk'),
        ),
    ]
