# Generated by Django 4.2.4 on 2023-08-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='tranche',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='stay',
            name='checkin',
            field=models.DateTimeField(verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='checkout',
            field=models.DateTimeField(verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='tranche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.tranche'),
        ),
        migrations.AlterField(
            model_name='tranche',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tranche',
            name='short_descr',
            field=models.CharField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.website'),
        ),
    ]
