# Generated by Django 4.2.4 on 2023-08-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_website_alter_tranche_options_alter_stay_checkin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stay',
            options={'ordering': ['checkin']},
        ),
        migrations.AlterField(
            model_name='stay',
            name='cancel_before',
            field=models.DateTimeField(verbose_name='Cancel before (local time)'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='checkin',
            field=models.DateTimeField(verbose_name='Check-in (local time)'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='checkout',
            field=models.DateTimeField(verbose_name='Check-out (local time)'),
        ),
    ]
