# Generated by Django 4.2.4 on 2023-09-13 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_stay_options_alter_stay_cancel_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
