# Generated by Django 4.2.4 on 2023-09-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_stay_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
