# Generated by Django 4.2.4 on 2023-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_stay_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='payment_date',
            field=models.DateField(verbose_name='Payment date (local time)'),
        ),
    ]
