# Generated by Django 4.2.5 on 2023-09-13 17:55

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_sidetrip_latitude_sidetrip_longitude_stay_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidetrip',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sidetrip',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='longitude',
        ),
        migrations.AddField(
            model_name='sidetrip',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
        migrations.AddField(
            model_name='stay',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
