# Generated by Django 4.2.5 on 2023-09-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_sidetrip_latitude_remove_sidetrip_longitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tranche',
            new_name='Leg',
        ),
    ]
