# Generated by Django 4.2.4 on 2023-09-13 09:15

from django.db import migrations, models
import django.db.models.deletion
import loader.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0006_alter_stay_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='stay',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='SideTrip',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date', models.DateField()),
                ('tranche', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loader.tranche')),
            ],
            # bases=(models.Model, loader.mixins.GeoItemModelMixin),
            bases=(loader.mixins.GeoItemModelMixin,),
        ),
    ]
