# Generated by Django 4.2.4 on 2023-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0007_remove_stay_latitude_remove_stay_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidetrip',
            name='latitude',
            field=models.FloatField(default=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidetrip',
            name='longitude',
            field=models.FloatField(default=139),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stay',
            name='latitude',
            field=models.FloatField(default=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stay',
            name='longitude',
            field=models.FloatField(default=139),
            preserve_default=False,
        ),
    ]
